backend:
  name: git-gateway
  repo: YunWU914/HSKB
  branch: main

media_folder: "mechanical-workshop/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "mechanical-workshop"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
