backend:
  name: github
  repo: YunWU914/HSKB
  branch: main
  base_url: https://api.netlify.com
  auth_scope: repo

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "文章"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
